version: "3.8"

services:
  booking_db:
    image: mysql:latest
    container_name: booking_db
    restart: always
    networks:
      - hdv_network
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_RANDOM_ROOT_PASSWORD: false
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1
      MYSQL_DATABASE: db_booking
    # ports:
    #   - "3306:3306"
    volumes:
      - booking-mysql-data:/var/lib/mysql

  booking_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking_service
    depends_on:
      - booking_db
    ports:
      - "3002:3002"
    networks:
      - hdv_network
    environment:
      IP: booking_service
      PORT: 3002
      DB_IP: booking_db
      DB_PORT: 3306
      DB_DIALECT: mysql
      DB_NAME: db_booking
      DB_USER: sa
      DB_PASS: 1
      DB_GEN: 1
      NGINX_IP: 192.168.1.8
      NGINX_PORT: 8080

networks:
  hdv_network:
    driver: bridge
volumes:
  booking-mysql-data:
